version: "3"
services:
  app:
    build: .
    container_name: todo-app
    environment:
      - DATABASE_URL=postgresql://hithere_owner:npg_AqCULDxKe91J@ep-dawn-silence-a4frmur0-pooler.us-east-1.aws.neon.tech/Todo?sslmode=require
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
