name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write # This is important for GitHub Pages deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
      
    - name: Create environment file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
        echo "PORT=5000" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma Client
      run: npx prisma generate
      
    - name: Build for GitHub Pages
      run: |
        # Create build directory
        mkdir -p build
        
        # Copy your application files to build directory
        cp -r src/* build/ || echo "No src directory"
        cp -r public/* build/ || echo "No public directory"
        cp index.html build/ || echo "No index.html file"
        
        # Create a simple index.html if it doesn't exist
        if [ ! -f build/index.html ]; then
          echo "<html><head><title>ToDo App</title></head><body><h1>ToDo App</h1><p>App is running!</p></body></html>" > build/index.html
        fi
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PORT: 5000
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build # Deploy the build directory
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}